### ISSUE TITLE
Pure Training Functions

### ISSUE THREAD

**Issue by alexander-g** [poets-ai/elegy#138]
Hi @cgarciae , do you think it's possible to implement **pure jittable** training functions in Elegy? i.e. a function that does not depend on or modifies global state:
`logs, new_parameters, new_state = train_fn(inputs, old_parameters, old_state)`

I see several reasons to have something like that:
1. It's simply in the spirit of Jax
2. Custom training loops
3. I am planning to create a Jax interpreter based on Vulkan. Jax has the nice feature that it translates all operations to XLA primitives, one would only need to implement them in other backends. This would enable running on non-Nvidia GPUs and even embedded hardware like Raspberry Pi or smartphones. I've already done some tests and it seems to work, however this would require the function to be pure and jittable.

I've taken a look at the `module.jit()` function, the `_jit_fn()` without the `wrapper` seems to come close to what I want but not exactly because it modifies global state. Does it really require `states_tuple` and `statics` parameters? The first one is literally not used, and the second one does not seem to get modified anywhere, or does it? Can we get rid of `.set_parameters()` in `model_base.py` and the global RNG key?

For the beginning it would be maybe enough to have a `clean_up()` function that gets called after tracing the jitted training function or a context manager which is basically what `wrapper()` already is. Would be of course better if it was completely pure.

**Comment by cgarciae** [comment]
Hey @alexander-g!

Just for some context, the main issue that `jit` and `value_and_grad` try to solve is capturing all the state and turning into inputs of a pure function, in this case `_jit_fun` is effectively pure. This pattern was taken from Objax and after a couple of iterations it was found to be simplify low-level code since it avoids having the `apply` method you see in other framework.

In regard to your points:

1. We found that it is somewhat hard to make things more functional and make certain thing easy for users but are very opened to new proposals regarding the Module system which has already changed 3 times.
2. @charlielito and I have been discussing offline having a well defined mechanism so users can implement custom training loop as in Keras [train_step](https://keras.io/guides/customizing_what_happens_in_fit)  and maybe we can get some inspiration from Pytorch Lightning. I think this can help a lot of users and is of interest to elegy in regards of what we can propose to make more exotic training schemes easier. 
3. Nice! I read a thread about vulkan support in XLA once but I guess its not there yet.
